ai: Conserve RAM by only restarting one set of api server daemons at a time.

diff --git a/ai/docker/apiserver/start b/ai/docker/apiserver/start
--- a/ai/docker/apiserver/start
+++ b/ai/docker/apiserver/start
@@ -24,12 +24,14 @@ if [ "$ADMIN_EMAIL" != None ]; then
     echo $HOST > /etc/mailname
     postconf -e "myhostname = $HOST"
     postconf -e "mynetworks ="
-    echo "root: $ADMIN_EMAIL" > /etc/aliases
-    newaliases
+    grep -q 'root:' /etc/aliases || echo "root: $ADMIN_EMAIL" >> /etc/aliases
 else
     # Relay message to console.
-    chmod o+w /dev/console
-    echo "root: /dev/console" > /etc/aliases
+    if ! chmod o+w /dev/console; then
+        echo 'Try docker run -t ...'
+        exit 1
+    fi
+    grep -q 'root:' /etc/aliases || echo "root: /dev/console" >> /etc/aliases
 fi
 newaliases
 # Need postfix running to relay message to console even if no admin.
@@ -37,4 +39,6 @@ service postfix start >/dev/null 2>&1
 
 cron
 
-su -l aiplanner -c "$AI_DIR/docker/deploy/start.aiplanner $@"
+su -l aiplanner -c "$AI_DIR/docker/apiserver/start.aiplanner $@"
+
+exit 1 # Inform docker of failure.
